platform :ios, '12.0'

use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/HenkBoxma/rigi-ios-pod.git'

def shared_pods
  # Add shared pods here
end

target 'RigiExample' do
  shared_pods
end

target 'RigiExample Pseudo' do
  shared_pods
  pod 'Rigi'
end
